# Site settings
title: Ganesh Datta
header-img: img/avila-beach-pier.jpg
email: me@ganeshdatta.com
description: "I'm Ganesh Datta. An aspiring entrepreneur who's working on all kinds of stuff. Here I write about recent technologies I've used and any tips and tricks I've come across as I work on my projects. Hope they're useful!"
baseurl: ""
url: "http://ganeshdatta.com"
twitter_username: gsdatta
github_username:  gsdatta
facebook_username: ganeshsdatta
linkedin_username: gsdatta

# Build settings
markdown: kramdown
# highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
